version: "3"
services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
