version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/db?sslmode=disable
    ports:
      - 8081:8081
    restart: on-failure:3
